<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="61889" started-at="2020-02-02T16:20:07Z" finished-at="2020-02-02T16:21:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="61889" started-at="2020-02-02T16:20:07Z" finished-at="2020-02-02T16:21:08Z">
      <class name="screenShotFailed.ScreenShotFailed">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:screenShotFailed.ScreenShotFailed@6f7fd0e6]" name="startBrowser" is-config="true" duration-ms="17546" started-at="2020-02-02T21:50:07Z" finished-at="2020-02-02T21:50:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="FAIL" signature="testCase1()[pri:0, instance:screenShotFailed.ScreenShotFailed@6f7fd0e6]" name="testCase1" duration-ms="21525" started-at="2020-02-02T21:50:24Z" finished-at="2020-02-02T21:50:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	test case 1 fail expected [zyx] but found [xyz],
	test case 1 fail expected [zyx] but found [xyz]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	test case 1 fail expected [zyx] but found [xyz],
	test case 1 fail expected [zyx] but found [xyz]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at screenShotFailed.ScreenShotFailed.testCase1(ScreenShotFailed.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:screenShotFailed.ScreenShotFailed@6f7fd0e6]" name="closeBrowser" is-config="true" duration-ms="1248" started-at="2020-02-02T21:50:48Z" finished-at="2020-02-02T21:50:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:screenShotFailed.ScreenShotFailed@6f7fd0e6]" name="startBrowser" is-config="true" duration-ms="17057" started-at="2020-02-02T21:50:49Z" finished-at="2020-02-02T21:51:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="FAIL" signature="testCase2()[pri:0, instance:screenShotFailed.ScreenShotFailed@6f7fd0e6]" name="testCase2" duration-ms="516" started-at="2020-02-02T21:51:06Z" finished-at="2020-02-02T21:51:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[testcase 2 failed expected [zyx] but found [xyz]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: testcase 2 failed expected [zyx] but found [xyz]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at screenShotFailed.ScreenShotFailed.testCase2(ScreenShotFailed.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:screenShotFailed.ScreenShotFailed@6f7fd0e6]" name="closeBrowser" is-config="true" duration-ms="1218" started-at="2020-02-02T21:51:07Z" finished-at="2020-02-02T21:51:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- screenShotFailed.ScreenShotFailed -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
