<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testng.A" tests="5" time="130.386" ignored="2" failures="1" timestamp="10 Jan 2020 06:07:59 GMT" skipped="3" hostname="LAPTOP-K28EKLKS" errors="0">
  <testcase name="tc4" time="25.444" classname="testng.A">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase name="tc4" time="40.143" classname="testng.A">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [abcd@gmail.com] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [abcd@gmail.com] but found [null]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testng.A.tc4(A.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- tc4 -->
  <testcase name="tc3" time="19.193" classname="testng.A"/>
  <testcase name="tc4" time="21.298" classname="testng.A">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase name="tc4" time="24.308" classname="testng.A">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase name="tc1" classname="testng.A">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc2" classname="testng.A">
    <skipped/>
  </testcase> <!-- tc2 -->
</testsuite> <!-- testng.A -->
